# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/ClientMapSendData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class ClientMapSendData(genpy.Message):
  _md5sum = "5ccfd8a27a3d104fd1e8e4702a1b153a"
  _type = "rm_msgs/ClientMapSendData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 KEY_A = 65
uint8 KEY_H = 72
uint8 KEY_K = 75
uint8 KEY_L = 76
uint8 KEY_N = 78
uint8 KEY_O = 79
uint8 KEY_U = 85

float32 target_position_x
float32 target_position_y
float32 target_position_z
uint8 command_keyboard
uint16 target_robot_ID

time stamp
"""
  # Pseudo-constants
  KEY_A = 65
  KEY_H = 72
  KEY_K = 75
  KEY_L = 76
  KEY_N = 78
  KEY_O = 79
  KEY_U = 85

  __slots__ = ['target_position_x','target_position_y','target_position_z','command_keyboard','target_robot_ID','stamp']
  _slot_types = ['float32','float32','float32','uint8','uint16','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       target_position_x,target_position_y,target_position_z,command_keyboard,target_robot_ID,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ClientMapSendData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.target_position_x is None:
        self.target_position_x = 0.
      if self.target_position_y is None:
        self.target_position_y = 0.
      if self.target_position_z is None:
        self.target_position_z = 0.
      if self.command_keyboard is None:
        self.command_keyboard = 0
      if self.target_robot_ID is None:
        self.target_robot_ID = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.target_position_x = 0.
      self.target_position_y = 0.
      self.target_position_z = 0.
      self.command_keyboard = 0
      self.target_robot_ID = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3fBH2I().pack(_x.target_position_x, _x.target_position_y, _x.target_position_z, _x.command_keyboard, _x.target_robot_ID, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 23
      (_x.target_position_x, _x.target_position_y, _x.target_position_z, _x.command_keyboard, _x.target_robot_ID, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_3fBH2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3fBH2I().pack(_x.target_position_x, _x.target_position_y, _x.target_position_z, _x.command_keyboard, _x.target_robot_ID, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 23
      (_x.target_position_x, _x.target_position_y, _x.target_position_z, _x.command_keyboard, _x.target_robot_ID, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_3fBH2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fBH2I = None
def _get_struct_3fBH2I():
    global _struct_3fBH2I
    if _struct_3fBH2I is None:
        _struct_3fBH2I = struct.Struct("<3fBH2I")
    return _struct_3fBH2I
