# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/MultiDofCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg

class MultiDofCmd(genpy.Message):
  _md5sum = "0ef5d8d462010858e9cd0f8a34969a34"
  _type = "rm_msgs/MultiDofCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 VELOCITY = 0
uint8 POSITION = 1

time stamp
uint8 mode

# VELOCITY/POSITION
geometry_msgs/Vector3 linear
geometry_msgs/Vector3 angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  # Pseudo-constants
  VELOCITY = 0
  POSITION = 1

  __slots__ = ['stamp','mode','linear','angular']
  _slot_types = ['time','uint8','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,mode,linear,angular

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MultiDofCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.mode is None:
        self.mode = 0
      if self.linear is None:
        self.linear = geometry_msgs.msg.Vector3()
      if self.angular is None:
        self.angular = geometry_msgs.msg.Vector3()
    else:
      self.stamp = genpy.Time()
      self.mode = 0
      self.linear = geometry_msgs.msg.Vector3()
      self.angular = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2IB6d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.mode, _x.linear.x, _x.linear.y, _x.linear.z, _x.angular.x, _x.angular.y, _x.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.linear is None:
        self.linear = geometry_msgs.msg.Vector3()
      if self.angular is None:
        self.angular = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.stamp.secs, _x.stamp.nsecs, _x.mode, _x.linear.x, _x.linear.y, _x.linear.z, _x.angular.x, _x.angular.y, _x.angular.z,) = _get_struct_2IB6d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2IB6d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.mode, _x.linear.x, _x.linear.y, _x.linear.z, _x.angular.x, _x.angular.y, _x.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.linear is None:
        self.linear = geometry_msgs.msg.Vector3()
      if self.angular is None:
        self.angular = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.stamp.secs, _x.stamp.nsecs, _x.mode, _x.linear.x, _x.linear.y, _x.linear.z, _x.angular.x, _x.angular.y, _x.angular.z,) = _get_struct_2IB6d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2IB6d = None
def _get_struct_2IB6d():
    global _struct_2IB6d
    if _struct_2IB6d is None:
        _struct_2IB6d = struct.Struct("<2IB6d")
    return _struct_2IB6d
