# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/PowerManagementSystemExceptionData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class PowerManagementSystemExceptionData(genpy.Message):
  _md5sum = "48dc20c9346b76eeb74bcfd0aefcc86d"
  _type = "rm_msgs/PowerManagementSystemExceptionData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 r0
uint32 r1
uint32 r2
uint32 r3
uint32 r12
uint32 LR
uint32 PC
uint32 PSR

time stamp
"""
  __slots__ = ['r0','r1','r2','r3','r12','LR','PC','PSR','stamp']
  _slot_types = ['uint32','uint32','uint32','uint32','uint32','uint32','uint32','uint32','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       r0,r1,r2,r3,r12,LR,PC,PSR,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PowerManagementSystemExceptionData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.r0 is None:
        self.r0 = 0
      if self.r1 is None:
        self.r1 = 0
      if self.r2 is None:
        self.r2 = 0
      if self.r3 is None:
        self.r3 = 0
      if self.r12 is None:
        self.r12 = 0
      if self.LR is None:
        self.LR = 0
      if self.PC is None:
        self.PC = 0
      if self.PSR is None:
        self.PSR = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.r0 = 0
      self.r1 = 0
      self.r2 = 0
      self.r3 = 0
      self.r12 = 0
      self.LR = 0
      self.PC = 0
      self.PSR = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_10I().pack(_x.r0, _x.r1, _x.r2, _x.r3, _x.r12, _x.LR, _x.PC, _x.PSR, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.r0, _x.r1, _x.r2, _x.r3, _x.r12, _x.LR, _x.PC, _x.PSR, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_10I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_10I().pack(_x.r0, _x.r1, _x.r2, _x.r3, _x.r12, _x.LR, _x.PC, _x.PSR, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.r0, _x.r1, _x.r2, _x.r3, _x.r12, _x.LR, _x.PC, _x.PSR, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_10I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10I = None
def _get_struct_10I():
    global _struct_10I
    if _struct_10I is None:
        _struct_10I = struct.Struct("<10I")
    return _struct_10I
