# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/RadarMarkData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class RadarMarkData(genpy.Message):
  _md5sum = "ba5ba5eccc4c7646a706793847c5dce0"
  _type = "rm_msgs/RadarMarkData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 mark_hero_progress
uint8 mark_engineer_progress
uint8 mark_standard_3_progress
uint8 mark_standard_4_progress
uint8 mark_standard_5_progress
uint8 mark_sentry_progress

time stamp
"""
  __slots__ = ['mark_hero_progress','mark_engineer_progress','mark_standard_3_progress','mark_standard_4_progress','mark_standard_5_progress','mark_sentry_progress','stamp']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mark_hero_progress,mark_engineer_progress,mark_standard_3_progress,mark_standard_4_progress,mark_standard_5_progress,mark_sentry_progress,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RadarMarkData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mark_hero_progress is None:
        self.mark_hero_progress = 0
      if self.mark_engineer_progress is None:
        self.mark_engineer_progress = 0
      if self.mark_standard_3_progress is None:
        self.mark_standard_3_progress = 0
      if self.mark_standard_4_progress is None:
        self.mark_standard_4_progress = 0
      if self.mark_standard_5_progress is None:
        self.mark_standard_5_progress = 0
      if self.mark_sentry_progress is None:
        self.mark_sentry_progress = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.mark_hero_progress = 0
      self.mark_engineer_progress = 0
      self.mark_standard_3_progress = 0
      self.mark_standard_4_progress = 0
      self.mark_standard_5_progress = 0
      self.mark_sentry_progress = 0
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6B2I().pack(_x.mark_hero_progress, _x.mark_engineer_progress, _x.mark_standard_3_progress, _x.mark_standard_4_progress, _x.mark_standard_5_progress, _x.mark_sentry_progress, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 14
      (_x.mark_hero_progress, _x.mark_engineer_progress, _x.mark_standard_3_progress, _x.mark_standard_4_progress, _x.mark_standard_5_progress, _x.mark_sentry_progress, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_6B2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6B2I().pack(_x.mark_hero_progress, _x.mark_engineer_progress, _x.mark_standard_3_progress, _x.mark_standard_4_progress, _x.mark_standard_5_progress, _x.mark_sentry_progress, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 14
      (_x.mark_hero_progress, _x.mark_engineer_progress, _x.mark_standard_3_progress, _x.mark_standard_4_progress, _x.mark_standard_5_progress, _x.mark_sentry_progress, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_6B2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6B2I = None
def _get_struct_6B2I():
    global _struct_6B2I
    if _struct_6B2I is None:
        _struct_6B2I = struct.Struct("<6B2I")
    return _struct_6B2I
