# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rm_msgs/RobotsPositionData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class RobotsPositionData(genpy.Message):
  _md5sum = "e7f2d67005a1f99559daa95d34395f2e"
  _type = "rm_msgs/RobotsPositionData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 hero_x
float32 hero_y
float32 engineer_x
float32 engineer_y
float32 standard_3_x
float32 standard_3_y
float32 standard_4_x
float32 standard_4_y
float32 standard_5_x
float32 standard_5_y

time stamp
"""
  __slots__ = ['hero_x','hero_y','engineer_x','engineer_y','standard_3_x','standard_3_y','standard_4_x','standard_4_y','standard_5_x','standard_5_y','stamp']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hero_x,hero_y,engineer_x,engineer_y,standard_3_x,standard_3_y,standard_4_x,standard_4_y,standard_5_x,standard_5_y,stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotsPositionData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.hero_x is None:
        self.hero_x = 0.
      if self.hero_y is None:
        self.hero_y = 0.
      if self.engineer_x is None:
        self.engineer_x = 0.
      if self.engineer_y is None:
        self.engineer_y = 0.
      if self.standard_3_x is None:
        self.standard_3_x = 0.
      if self.standard_3_y is None:
        self.standard_3_y = 0.
      if self.standard_4_x is None:
        self.standard_4_x = 0.
      if self.standard_4_y is None:
        self.standard_4_y = 0.
      if self.standard_5_x is None:
        self.standard_5_x = 0.
      if self.standard_5_y is None:
        self.standard_5_y = 0.
      if self.stamp is None:
        self.stamp = genpy.Time()
    else:
      self.hero_x = 0.
      self.hero_y = 0.
      self.engineer_x = 0.
      self.engineer_y = 0.
      self.standard_3_x = 0.
      self.standard_3_y = 0.
      self.standard_4_x = 0.
      self.standard_4_y = 0.
      self.standard_5_x = 0.
      self.standard_5_y = 0.
      self.stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_10f2I().pack(_x.hero_x, _x.hero_y, _x.engineer_x, _x.engineer_y, _x.standard_3_x, _x.standard_3_y, _x.standard_4_x, _x.standard_4_y, _x.standard_5_x, _x.standard_5_y, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.hero_x, _x.hero_y, _x.engineer_x, _x.engineer_y, _x.standard_3_x, _x.standard_3_y, _x.standard_4_x, _x.standard_4_y, _x.standard_5_x, _x.standard_5_y, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_10f2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_10f2I().pack(_x.hero_x, _x.hero_y, _x.engineer_x, _x.engineer_y, _x.standard_3_x, _x.standard_3_y, _x.standard_4_x, _x.standard_4_y, _x.standard_5_x, _x.standard_5_y, _x.stamp.secs, _x.stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.hero_x, _x.hero_y, _x.engineer_x, _x.engineer_y, _x.standard_3_x, _x.standard_3_y, _x.standard_4_x, _x.standard_4_y, _x.standard_5_x, _x.standard_5_y, _x.stamp.secs, _x.stamp.nsecs,) = _get_struct_10f2I().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10f2I = None
def _get_struct_10f2I():
    global _struct_10f2I
    if _struct_10f2I is None:
        _struct_10f2I = struct.Struct("<10f2I")
    return _struct_10f2I
