// Generated by gencpp from file rm_msgs/ClientMapReceiveData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_CLIENTMAPRECEIVEDATA_H
#define RM_MSGS_MESSAGE_CLIENTMAPRECEIVEDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct ClientMapReceiveData_
{
  typedef ClientMapReceiveData_<ContainerAllocator> Type;

  ClientMapReceiveData_()
    : target_robot_ID(0)
    , target_position_x(0.0)
    , target_position_y(0.0)
    , stamp()  {
    }
  ClientMapReceiveData_(const ContainerAllocator& _alloc)
    : target_robot_ID(0)
    , target_position_x(0.0)
    , target_position_y(0.0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint16_t _target_robot_ID_type;
  _target_robot_ID_type target_robot_ID;

   typedef float _target_position_x_type;
  _target_position_x_type target_position_x;

   typedef float _target_position_y_type;
  _target_position_y_type target_position_y;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> const> ConstPtr;

}; // struct ClientMapReceiveData_

typedef ::rm_msgs::ClientMapReceiveData_<std::allocator<void> > ClientMapReceiveData;

typedef boost::shared_ptr< ::rm_msgs::ClientMapReceiveData > ClientMapReceiveDataPtr;
typedef boost::shared_ptr< ::rm_msgs::ClientMapReceiveData const> ClientMapReceiveDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator1> & lhs, const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator2> & rhs)
{
  return lhs.target_robot_ID == rhs.target_robot_ID &&
    lhs.target_position_x == rhs.target_position_x &&
    lhs.target_position_y == rhs.target_position_y &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator1> & lhs, const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c57a5847a34ebf54851115481ec4e6ab";
  }

  static const char* value(const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc57a5847a34ebf54ULL;
  static const uint64_t static_value2 = 0x851115481ec4e6abULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/ClientMapReceiveData";
  }

  static const char* value(const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 target_robot_ID\n"
"float32 target_position_x\n"
"float32 target_position_y\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_robot_ID);
      stream.next(m.target_position_x);
      stream.next(m.target_position_y);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClientMapReceiveData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::ClientMapReceiveData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::ClientMapReceiveData_<ContainerAllocator>& v)
  {
    s << indent << "target_robot_ID: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.target_robot_ID);
    s << indent << "target_position_x: ";
    Printer<float>::stream(s, indent + "  ", v.target_position_x);
    s << indent << "target_position_y: ";
    Printer<float>::stream(s, indent + "  ", v.target_position_y);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_CLIENTMAPRECEIVEDATA_H
