// Generated by gencpp from file rm_msgs/EnableGyro.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_ENABLEGYRO_H
#define RM_MSGS_MESSAGE_ENABLEGYRO_H

#include <ros/service_traits.h>


#include <rm_msgs/EnableGyroRequest.h>
#include <rm_msgs/EnableGyroResponse.h>


namespace rm_msgs
{

struct EnableGyro
{

typedef EnableGyroRequest Request;
typedef EnableGyroResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableGyro
} // namespace rm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rm_msgs::EnableGyro > {
  static const char* value()
  {
    return "b392a2bc1a18f8fd0a5d7f696d80a69d";
  }

  static const char* value(const ::rm_msgs::EnableGyro&) { return value(); }
};

template<>
struct DataType< ::rm_msgs::EnableGyro > {
  static const char* value()
  {
    return "rm_msgs/EnableGyro";
  }

  static const char* value(const ::rm_msgs::EnableGyro&) { return value(); }
};


// service_traits::MD5Sum< ::rm_msgs::EnableGyroRequest> should match
// service_traits::MD5Sum< ::rm_msgs::EnableGyro >
template<>
struct MD5Sum< ::rm_msgs::EnableGyroRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rm_msgs::EnableGyro >::value();
  }
  static const char* value(const ::rm_msgs::EnableGyroRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rm_msgs::EnableGyroRequest> should match
// service_traits::DataType< ::rm_msgs::EnableGyro >
template<>
struct DataType< ::rm_msgs::EnableGyroRequest>
{
  static const char* value()
  {
    return DataType< ::rm_msgs::EnableGyro >::value();
  }
  static const char* value(const ::rm_msgs::EnableGyroRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rm_msgs::EnableGyroResponse> should match
// service_traits::MD5Sum< ::rm_msgs::EnableGyro >
template<>
struct MD5Sum< ::rm_msgs::EnableGyroResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rm_msgs::EnableGyro >::value();
  }
  static const char* value(const ::rm_msgs::EnableGyroResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rm_msgs::EnableGyroResponse> should match
// service_traits::DataType< ::rm_msgs::EnableGyro >
template<>
struct DataType< ::rm_msgs::EnableGyroResponse>
{
  static const char* value()
  {
    return DataType< ::rm_msgs::EnableGyro >::value();
  }
  static const char* value(const ::rm_msgs::EnableGyroResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RM_MSGS_MESSAGE_ENABLEGYRO_H
