// Generated by gencpp from file rm_msgs/PowerManagementProcessStackOverflowData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_POWERMANAGEMENTPROCESSSTACKOVERFLOWDATA_H
#define RM_MSGS_MESSAGE_POWERMANAGEMENTPROCESSSTACKOVERFLOWDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct PowerManagementProcessStackOverflowData_
{
  typedef PowerManagementProcessStackOverflowData_<ContainerAllocator> Type;

  PowerManagementProcessStackOverflowData_()
    : process_name()
    , stamp()  {
    }
  PowerManagementProcessStackOverflowData_(const ContainerAllocator& _alloc)
    : process_name(_alloc)
    , stamp()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _process_name_type;
  _process_name_type process_name;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> const> ConstPtr;

}; // struct PowerManagementProcessStackOverflowData_

typedef ::rm_msgs::PowerManagementProcessStackOverflowData_<std::allocator<void> > PowerManagementProcessStackOverflowData;

typedef boost::shared_ptr< ::rm_msgs::PowerManagementProcessStackOverflowData > PowerManagementProcessStackOverflowDataPtr;
typedef boost::shared_ptr< ::rm_msgs::PowerManagementProcessStackOverflowData const> PowerManagementProcessStackOverflowDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator1> & lhs, const ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator2> & rhs)
{
  return lhs.process_name == rhs.process_name &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator1> & lhs, const ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3888ad0e8184067e8398c12c0b5e2afe";
  }

  static const char* value(const ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3888ad0e8184067eULL;
  static const uint64_t static_value2 = 0x8398c12c0b5e2afeULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/PowerManagementProcessStackOverflowData";
  }

  static const char* value(const ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string process_name\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.process_name);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PowerManagementProcessStackOverflowData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::PowerManagementProcessStackOverflowData_<ContainerAllocator>& v)
  {
    s << indent << "process_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.process_name);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_POWERMANAGEMENTPROCESSSTACKOVERFLOWDATA_H
