// Generated by gencpp from file rm_msgs/PowerManagementInitializationExceptionData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_POWERMANAGEMENTINITIALIZATIONEXCEPTIONDATA_H
#define RM_MSGS_MESSAGE_POWERMANAGEMENTINITIALIZATIONEXCEPTIONDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct PowerManagementInitializationExceptionData_
{
  typedef PowerManagementInitializationExceptionData_<ContainerAllocator> Type;

  PowerManagementInitializationExceptionData_()
    : error_code(0)
    , string()
    , stamp()  {
    }
  PowerManagementInitializationExceptionData_(const ContainerAllocator& _alloc)
    : error_code(0)
    , string(_alloc)
    , stamp()  {
  (void)_alloc;
    }



   typedef int8_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _string_type;
  _string_type string;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> const> ConstPtr;

}; // struct PowerManagementInitializationExceptionData_

typedef ::rm_msgs::PowerManagementInitializationExceptionData_<std::allocator<void> > PowerManagementInitializationExceptionData;

typedef boost::shared_ptr< ::rm_msgs::PowerManagementInitializationExceptionData > PowerManagementInitializationExceptionDataPtr;
typedef boost::shared_ptr< ::rm_msgs::PowerManagementInitializationExceptionData const> PowerManagementInitializationExceptionDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator1> & lhs, const ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator2> & rhs)
{
  return lhs.error_code == rhs.error_code &&
    lhs.string == rhs.string &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator1> & lhs, const ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54a71420468ddead2ca3dd2998bc282b";
  }

  static const char* value(const ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54a71420468ddeadULL;
  static const uint64_t static_value2 = 0x2ca3dd2998bc282bULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/PowerManagementInitializationExceptionData";
  }

  static const char* value(const ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 error_code\n"
"string string\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
      stream.next(m.string);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PowerManagementInitializationExceptionData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::PowerManagementInitializationExceptionData_<ContainerAllocator>& v)
  {
    s << indent << "error_code: ";
    Printer<int8_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.string);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_POWERMANAGEMENTINITIALIZATIONEXCEPTIONDATA_H
