// Generated by gencpp from file rm_msgs/RadarMarkData.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_RADARMARKDATA_H
#define RM_MSGS_MESSAGE_RADARMARKDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct RadarMarkData_
{
  typedef RadarMarkData_<ContainerAllocator> Type;

  RadarMarkData_()
    : mark_hero_progress(0)
    , mark_engineer_progress(0)
    , mark_standard_3_progress(0)
    , mark_standard_4_progress(0)
    , mark_standard_5_progress(0)
    , mark_sentry_progress(0)
    , stamp()  {
    }
  RadarMarkData_(const ContainerAllocator& _alloc)
    : mark_hero_progress(0)
    , mark_engineer_progress(0)
    , mark_standard_3_progress(0)
    , mark_standard_4_progress(0)
    , mark_standard_5_progress(0)
    , mark_sentry_progress(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint8_t _mark_hero_progress_type;
  _mark_hero_progress_type mark_hero_progress;

   typedef uint8_t _mark_engineer_progress_type;
  _mark_engineer_progress_type mark_engineer_progress;

   typedef uint8_t _mark_standard_3_progress_type;
  _mark_standard_3_progress_type mark_standard_3_progress;

   typedef uint8_t _mark_standard_4_progress_type;
  _mark_standard_4_progress_type mark_standard_4_progress;

   typedef uint8_t _mark_standard_5_progress_type;
  _mark_standard_5_progress_type mark_standard_5_progress;

   typedef uint8_t _mark_sentry_progress_type;
  _mark_sentry_progress_type mark_sentry_progress;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::rm_msgs::RadarMarkData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::RadarMarkData_<ContainerAllocator> const> ConstPtr;

}; // struct RadarMarkData_

typedef ::rm_msgs::RadarMarkData_<std::allocator<void> > RadarMarkData;

typedef boost::shared_ptr< ::rm_msgs::RadarMarkData > RadarMarkDataPtr;
typedef boost::shared_ptr< ::rm_msgs::RadarMarkData const> RadarMarkDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::RadarMarkData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::RadarMarkData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::RadarMarkData_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarMarkData_<ContainerAllocator2> & rhs)
{
  return lhs.mark_hero_progress == rhs.mark_hero_progress &&
    lhs.mark_engineer_progress == rhs.mark_engineer_progress &&
    lhs.mark_standard_3_progress == rhs.mark_standard_3_progress &&
    lhs.mark_standard_4_progress == rhs.mark_standard_4_progress &&
    lhs.mark_standard_5_progress == rhs.mark_standard_5_progress &&
    lhs.mark_sentry_progress == rhs.mark_sentry_progress &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::RadarMarkData_<ContainerAllocator1> & lhs, const ::rm_msgs::RadarMarkData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarMarkData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::RadarMarkData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarMarkData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::RadarMarkData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarMarkData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::RadarMarkData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::RadarMarkData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba5ba5eccc4c7646a706793847c5dce0";
  }

  static const char* value(const ::rm_msgs::RadarMarkData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba5ba5eccc4c7646ULL;
  static const uint64_t static_value2 = 0xa706793847c5dce0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::RadarMarkData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/RadarMarkData";
  }

  static const char* value(const ::rm_msgs::RadarMarkData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::RadarMarkData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mark_hero_progress\n"
"uint8 mark_engineer_progress\n"
"uint8 mark_standard_3_progress\n"
"uint8 mark_standard_4_progress\n"
"uint8 mark_standard_5_progress\n"
"uint8 mark_sentry_progress\n"
"\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::RadarMarkData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::RadarMarkData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mark_hero_progress);
      stream.next(m.mark_engineer_progress);
      stream.next(m.mark_standard_3_progress);
      stream.next(m.mark_standard_4_progress);
      stream.next(m.mark_standard_5_progress);
      stream.next(m.mark_sentry_progress);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarMarkData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::RadarMarkData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::RadarMarkData_<ContainerAllocator>& v)
  {
    s << indent << "mark_hero_progress: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mark_hero_progress);
    s << indent << "mark_engineer_progress: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mark_engineer_progress);
    s << indent << "mark_standard_3_progress: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mark_standard_3_progress);
    s << indent << "mark_standard_4_progress: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mark_standard_4_progress);
    s << indent << "mark_standard_5_progress: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mark_standard_5_progress);
    s << indent << "mark_sentry_progress: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mark_sentry_progress);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_RADARMARKDATA_H
