// Generated by gencpp from file rm_msgs/SetLimitVel.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_SETLIMITVEL_H
#define RM_MSGS_MESSAGE_SETLIMITVEL_H

#include <ros/service_traits.h>


#include <rm_msgs/SetLimitVelRequest.h>
#include <rm_msgs/SetLimitVelResponse.h>


namespace rm_msgs
{

struct SetLimitVel
{

typedef SetLimitVelRequest Request;
typedef SetLimitVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLimitVel
} // namespace rm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rm_msgs::SetLimitVel > {
  static const char* value()
  {
    return "af5f6a722311e0f309d615a26441d6e9";
  }

  static const char* value(const ::rm_msgs::SetLimitVel&) { return value(); }
};

template<>
struct DataType< ::rm_msgs::SetLimitVel > {
  static const char* value()
  {
    return "rm_msgs/SetLimitVel";
  }

  static const char* value(const ::rm_msgs::SetLimitVel&) { return value(); }
};


// service_traits::MD5Sum< ::rm_msgs::SetLimitVelRequest> should match
// service_traits::MD5Sum< ::rm_msgs::SetLimitVel >
template<>
struct MD5Sum< ::rm_msgs::SetLimitVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rm_msgs::SetLimitVel >::value();
  }
  static const char* value(const ::rm_msgs::SetLimitVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rm_msgs::SetLimitVelRequest> should match
// service_traits::DataType< ::rm_msgs::SetLimitVel >
template<>
struct DataType< ::rm_msgs::SetLimitVelRequest>
{
  static const char* value()
  {
    return DataType< ::rm_msgs::SetLimitVel >::value();
  }
  static const char* value(const ::rm_msgs::SetLimitVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rm_msgs::SetLimitVelResponse> should match
// service_traits::MD5Sum< ::rm_msgs::SetLimitVel >
template<>
struct MD5Sum< ::rm_msgs::SetLimitVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rm_msgs::SetLimitVel >::value();
  }
  static const char* value(const ::rm_msgs::SetLimitVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rm_msgs::SetLimitVelResponse> should match
// service_traits::DataType< ::rm_msgs::SetLimitVel >
template<>
struct DataType< ::rm_msgs::SetLimitVelResponse>
{
  static const char* value()
  {
    return DataType< ::rm_msgs::SetLimitVel >::value();
  }
  static const char* value(const ::rm_msgs::SetLimitVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RM_MSGS_MESSAGE_SETLIMITVEL_H
