// Generated by gencpp from file rm_msgs/ShootState.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_SHOOTSTATE_H
#define RM_MSGS_MESSAGE_SHOOTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct ShootState_
{
  typedef ShootState_<ContainerAllocator> Type;

  ShootState_()
    : state(0)
    , stamp()  {
    }
  ShootState_(const ContainerAllocator& _alloc)
    : state(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(READY)
  #undef READY
#endif
#if defined(_WIN32) && defined(PUSH)
  #undef PUSH
#endif
#if defined(_WIN32) && defined(BLOCK)
  #undef BLOCK
#endif

  enum {
    STOP = 0u,
    READY = 1u,
    PUSH = 2u,
    BLOCK = 3u,
  };


  typedef boost::shared_ptr< ::rm_msgs::ShootState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::ShootState_<ContainerAllocator> const> ConstPtr;

}; // struct ShootState_

typedef ::rm_msgs::ShootState_<std::allocator<void> > ShootState;

typedef boost::shared_ptr< ::rm_msgs::ShootState > ShootStatePtr;
typedef boost::shared_ptr< ::rm_msgs::ShootState const> ShootStateConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::ShootState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::ShootState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::ShootState_<ContainerAllocator1> & lhs, const ::rm_msgs::ShootState_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::ShootState_<ContainerAllocator1> & lhs, const ::rm_msgs::ShootState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ShootState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::ShootState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ShootState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::ShootState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ShootState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::ShootState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::ShootState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b15fb3b0295db9ecded84ae23a7dcfc0";
  }

  static const char* value(const ::rm_msgs::ShootState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb15fb3b0295db9ecULL;
  static const uint64_t static_value2 = 0xded84ae23a7dcfc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::ShootState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/ShootState";
  }

  static const char* value(const ::rm_msgs::ShootState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::ShootState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 STOP = 0\n"
"uint8 READY = 1\n"
"uint8 PUSH = 2\n"
"uint8 BLOCK = 3\n"
"\n"
"uint8 state\n"
"time stamp\n"
;
  }

  static const char* value(const ::rm_msgs::ShootState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::ShootState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::ShootState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::ShootState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_SHOOTSTATE_H
