// Generated by gencpp from file rm_msgs/TagMsgArray.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_TAGMSGARRAY_H
#define RM_MSGS_MESSAGE_TAGMSGARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rm_msgs/TagMsg.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct TagMsgArray_
{
  typedef TagMsgArray_<ContainerAllocator> Type;

  TagMsgArray_()
    : header()
    , tag_msgs_array()  {
    }
  TagMsgArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tag_msgs_array(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::rm_msgs::TagMsg_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::rm_msgs::TagMsg_<ContainerAllocator> >> _tag_msgs_array_type;
  _tag_msgs_array_type tag_msgs_array;





  typedef boost::shared_ptr< ::rm_msgs::TagMsgArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::TagMsgArray_<ContainerAllocator> const> ConstPtr;

}; // struct TagMsgArray_

typedef ::rm_msgs::TagMsgArray_<std::allocator<void> > TagMsgArray;

typedef boost::shared_ptr< ::rm_msgs::TagMsgArray > TagMsgArrayPtr;
typedef boost::shared_ptr< ::rm_msgs::TagMsgArray const> TagMsgArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::TagMsgArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::TagMsgArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::TagMsgArray_<ContainerAllocator1> & lhs, const ::rm_msgs::TagMsgArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tag_msgs_array == rhs.tag_msgs_array;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::TagMsgArray_<ContainerAllocator1> & lhs, const ::rm_msgs::TagMsgArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::TagMsgArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::TagMsgArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::TagMsgArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::TagMsgArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::TagMsgArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::TagMsgArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::TagMsgArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "902a772db603bf3e4cf94e3aa203838c";
  }

  static const char* value(const ::rm_msgs::TagMsgArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x902a772db603bf3eULL;
  static const uint64_t static_value2 = 0x4cf94e3aa203838cULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::TagMsgArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/TagMsgArray";
  }

  static const char* value(const ::rm_msgs::TagMsgArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::TagMsgArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"TagMsg[] tag_msgs_array\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rm_msgs/TagMsg\n"
"uint8 color\n"
"uint8 letter\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rm_msgs::TagMsgArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::TagMsgArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tag_msgs_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TagMsgArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::TagMsgArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::TagMsgArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tag_msgs_array[]" << std::endl;
    for (size_t i = 0; i < v.tag_msgs_array.size(); ++i)
    {
      s << indent << "  tag_msgs_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rm_msgs::TagMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.tag_msgs_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_TAGMSGARRAY_H
