// Generated by gencpp from file rm_msgs/TargetDetection.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_TARGETDETECTION_H
#define RM_MSGS_MESSAGE_TARGETDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rm_msgs
{
template <class ContainerAllocator>
struct TargetDetection_
{
  typedef TargetDetection_<ContainerAllocator> Type;

  TargetDetection_()
    : id(0)
    , distance_to_image_center(0.0)
    , confidence(0.0)
    , is_large_armor(false)
    , pose()  {
    }
  TargetDetection_(const ContainerAllocator& _alloc)
    : id(0)
    , distance_to_image_center(0.0)
    , confidence(0.0)
    , is_large_armor(false)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef double _distance_to_image_center_type;
  _distance_to_image_center_type distance_to_image_center;

   typedef double _confidence_type;
  _confidence_type confidence;

   typedef uint8_t _is_large_armor_type;
  _is_large_armor_type is_large_armor;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::rm_msgs::TargetDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::TargetDetection_<ContainerAllocator> const> ConstPtr;

}; // struct TargetDetection_

typedef ::rm_msgs::TargetDetection_<std::allocator<void> > TargetDetection;

typedef boost::shared_ptr< ::rm_msgs::TargetDetection > TargetDetectionPtr;
typedef boost::shared_ptr< ::rm_msgs::TargetDetection const> TargetDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::TargetDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::TargetDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::TargetDetection_<ContainerAllocator1> & lhs, const ::rm_msgs::TargetDetection_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.distance_to_image_center == rhs.distance_to_image_center &&
    lhs.confidence == rhs.confidence &&
    lhs.is_large_armor == rhs.is_large_armor &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::TargetDetection_<ContainerAllocator1> & lhs, const ::rm_msgs::TargetDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::TargetDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::TargetDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::TargetDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::TargetDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::TargetDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::TargetDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::TargetDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d910a0b22b7be76ca063afd23388a35b";
  }

  static const char* value(const ::rm_msgs::TargetDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd910a0b22b7be76cULL;
  static const uint64_t static_value2 = 0xa063afd23388a35bULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::TargetDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/TargetDetection";
  }

  static const char* value(const ::rm_msgs::TargetDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::TargetDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"float64 distance_to_image_center\n"
"float64 confidence\n"
"bool is_large_armor\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rm_msgs::TargetDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::TargetDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.distance_to_image_center);
      stream.next(m.confidence);
      stream.next(m.is_large_armor);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::TargetDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::TargetDetection_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "distance_to_image_center: ";
    Printer<double>::stream(s, indent + "  ", v.distance_to_image_center);
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
    s << indent << "is_large_armor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_large_armor);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_TARGETDETECTION_H
