(cl:in-package rm_msgs-msg)
(cl:export '(ABNORMAL_RESET_REASON-VAL
          ABNORMAL_RESET_REASON
          STATE_MACHINE_BEFORE_RESET_MODE-VAL
          STATE_MACHINE_BEFORE_RESET_MODE
          POWER_MANAGEMENT_BEFORE_RESET_TOPOLOGY-VAL
          POWER_MANAGEMENT_BEFORE_RESET_TOPOLOGY
          STAMP-VAL
          STAMP
))