(cl:in-package rm_msgs-msg)
(cl:export '(RED_1_ROBOT_HP-VAL
          RED_1_ROBOT_HP
          RED_2_ROBOT_HP-VAL
          RED_2_ROBOT_HP
          RED_3_ROBOT_HP-VAL
          RED_3_ROBOT_HP
          RED_4_ROBOT_HP-VAL
          RED_4_ROBOT_HP
          RED_5_ROBOT_HP-VAL
          RED_5_ROBOT_HP
          RED_7_ROBOT_HP-VAL
          RED_7_ROBOT_HP
          RED_OUTPOST_HP-VAL
          RED_OUTPOST_HP
          RED_BASE_HP-VAL
          RED_BASE_HP
          BLUE_1_ROBOT_HP-VAL
          BLUE_1_ROBOT_HP
          BLUE_2_ROBOT_HP-VAL
          BLUE_2_ROBOT_HP
          BLUE_3_ROBOT_HP-VAL
          BLUE_3_ROBOT_HP
          BLUE_4_ROBOT_HP-VAL
          BLUE_4_ROBOT_HP
          BLUE_5_ROBOT_HP-VAL
          BLUE_5_ROBOT_HP
          BLUE_7_ROBOT_HP-VAL
          BLUE_7_ROBOT_HP
          BLUE_OUTPOST_HP-VAL
          BLUE_OUTPOST_HP
          BLUE_BASE_HP-VAL
          BLUE_BASE_HP
          STAMP-VAL
          STAMP
))