(cl:in-package rm_msgs-msg)
(cl:export '(CHASSIS_POWER-VAL
          CHASSIS_POWER
          CHASSIS_EXPECT_POWER-VAL
          CHASSIS_EXPECT_POWER
          CAPACITY_RECENT_CHARGE_POWER-VAL
          CAPACITY_RECENT_CHARGE_POWER
          CAPACITY_REMAIN_CHARGE-VAL
          CAPACITY_REMAIN_CHARGE
          CAPACITY_EXPECT_CHARGE_POWER-VAL
          CAPACITY_EXPECT_CHARGE_POWER
          STATE_MACHINE_RUNNING_STATE-VAL
          STATE_MACHINE_RUNNING_STATE
          POWER_MANAGEMENT_PROTECTION_INFO-VAL
          POWER_MANAGEMENT_PROTECTION_INFO
          POWER_MANAGEMENT_TOPOLOGY-VAL
          POWER_MANAGEMENT_TOPOLOGY
          STAMP-VAL
          STAMP
))