(cl:in-package rm_msgs-msg)
(cl:export '(MARK_HERO_PROGRESS-VAL
          MARK_HERO_PROGRESS
          MARK_ENGINEER_PROGRESS-VAL
          MARK_ENGINEER_PROGRESS
          MARK_STANDARD_3_PROGRESS-VAL
          MARK_STANDARD_3_PROGRESS
          MARK_STANDARD_4_PROGRESS-VAL
          MARK_STANDARD_4_PROGRESS
          MARK_STANDARD_5_PROGRESS-VAL
          MARK_STANDARD_5_PROGRESS
          MARK_SENTRY_PROGRESS-VAL
          MARK_SENTRY_PROGRESS
          STAMP-VAL
          STAMP
))