(cl:in-package rm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MODE-VAL
          MODE
          X-VAL
          X
          PHI-VAL
          PHI
          THETA-VAL
          THETA
          X_B_L-VAL
          X_B_L
          X_B_R-VAL
          X_B_R
          X_DOT-VAL
          X_DOT
          PHI_DOT-VAL
          PHI_DOT
          THETA_DOT-VAL
          THETA_DOT
          X_B_L_DOT-VAL
          X_B_L_DOT
          X_B_R_DOT-VAL
          X_B_R_DOT
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          T_L-VAL
          T_L
          T_R-VAL
          T_R
          F_B_L-VAL
          F_B_L
          F_B_R-VAL
          F_B_R
))