controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid:
    {
      p: 30,
      i: 0.0,
      d: 0.8,
      i_clamp_max: 1,
      i_clamp_min: -1,
      antiwindup: true,
    }
    joint_velocity_controller:
      type: effort_controllers/JointVelocityController
      joint: joint1
      pid: {p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true}